# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievancepost',
            old_name='updated_date',
            new_name='last_updated_date',
        ),
    ]
