# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_auto_20170901_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievancepost',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grievancepost',
            name='heading',
            field=models.CharField(max_length=50),
        ),
    ]
