# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_auto_20170901_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievancepost',
            name='department',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grievancepost',
            name='assigned_to',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
