# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0004_auto_20170901_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievancepost',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='grievancepost',
            name='department',
        ),
    ]
