# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0005_auto_20170901_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievancepost',
            name='assigned_to',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grievancepost',
            name='department',
            field=models.CharField(choices=[(b'Electricity', b'E'), (b'LAN', b'L'), (b'Hostel', b'H'), (b'Admin', b'A')], max_length=10, null=True),
        ),
    ]
