# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0006_auto_20170901_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievancepost',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grievancepost',
            name='department',
            field=models.CharField(choices=[(b'E', b'Electricity'), (b'LAN', b'LAN'), (b'H', b'Hostel'), (b'A', b'Admin')], max_length=10, null=True),
        ),
    ]
